package com.yhk.aistudyplanner.ai.service;
import com.fasterxml.jackson.databind.ObjectMapper;import com.yhk.aistudyplanner.ai.config.AiPlanningProperties;import com.yhk.aistudyplanner.ai.gateway.*;import com.yhk.aistudyplanner.ai.validator.AiPlanResponseValidator;import com.yhk.aistudyplanner.ai.vo.AiPlanningContext;import com.yhk.aistudyplanner.auth.service.AuthSessionService;import com.yhk.aistudyplanner.common.exception.*;import com.yhk.aistudyplanner.plan.dto.PlanDraftRequest;import com.yhk.aistudyplanner.plan.service.RuleBasedPlanGenerator;import com.yhk.aistudyplanner.plan.vo.*;import com.yhk.aistudyplanner.task.entity.TaskStatus;
import org.junit.jupiter.api.*;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;import org.mockito.junit.jupiter.MockitoExtension;import org.springframework.beans.factory.ObjectProvider;import java.time.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class AiPlanServiceTest {static final LocalDate DATE=LocalDate.of(2026,7,23);@Mock ObjectProvider<PlanningGateway> provider;@Mock PlanningGateway gateway;@Mock AuthSessionService session;@Mock AiPlanningContextService contexts;@Mock AiPlanPromptService prompts;@Mock RuleBasedPlanGenerator rules;AiPlanningProperties properties;AiPlanService service;PlanDraftRequest request;PlanDraftView rule;
 @BeforeEach void setUp(){properties=new AiPlanningProperties();properties.setEnabled(true);properties.setApiKey("test-key");when(session.currentUserId()).thenReturn(1L);request=new PlanDraftRequest(DATE,LocalTime.of(9,0),120,null);rule=new PlanDraftView("rule",DATE,LocalTime.of(9,0),120,60,null,"rule",List.of());lenient().when(rules.generate(1,request)).thenReturn(rule);lenient().when(prompts.system()).thenReturn("system JSON");lenient().when(prompts.user(any(),any())).thenReturn("user");service=new AiPlanService(properties,provider,session,contexts,prompts,new AiPlanResponseParser(new ObjectMapper()),new AiPlanResponseValidator(),rules,Clock.fixed(DATE.atStartOfDay(ZoneId.of("Asia/Shanghai")).toInstant(),ZoneId.of("Asia/Shanghai")));}
 @Test void disabledOrMissingKeyFallsBackWithoutCallingProvider(){properties.setEnabled(false);when(contexts.build(1,DATE)).thenReturn(context());var r=service.generate(request);assertTrue(r.fallbackUsed());assertEquals("RULE",r.generatorType());verify(provider,never()).getObject();}
 @Test void noCandidatesSkipsAiWithoutMarkingFailure(){when(contexts.build(1,DATE)).thenReturn(emptyContext());var r=service.generate(request);assertFalse(r.fallbackUsed());assertEquals("RULE",r.generatorType());verifyNoInteractions(gateway);}
 @Test void validJsonCreatesDeterministicDraft(){available();when(contexts.build(1,DATE)).thenReturn(context());when(gateway.generate(anyString(),anyString())).thenReturn("{\"summary\":\"ok\",\"items\":[{\"taskId\":10,\"plannedMinutes\":60,\"reason\":\"due\"},{\"taskId\":11,\"plannedMinutes\":45,\"reason\":\"progress\"}]}");var r=service.generate(request);assertEquals("AI",r.generatorType());assertFalse(r.fallbackUsed());assertEquals(105,r.draft().plannedMinutes());assertEquals(DATE.atTime(9,0),r.draft().items().get(0).startAt());assertEquals(r.draft().items().get(0).endAt(),r.draft().items().get(1).startAt());}
 @Test void emptyAndInvalidJsonFallback(){assertFallbackFor(null);assertFallbackFor("bad json");}
 @Test void inventedAndDuplicateTaskFallback(){assertFallbackFor(json("99,30,reason"));assertFallbackFor("{\"summary\":\"x\",\"items\":[{\"taskId\":10,\"plannedMinutes\":30,\"reason\":\"x\"},{\"taskId\":10,\"plannedMinutes\":30,\"reason\":\"x\"}]}");}
 @Test void shortOversizedAndBadReasonFallback(){assertFallbackFor(json("10,10,reason"));assertFallbackFor(json("10,90,reason"));assertFallbackFor(json("10,30,"));assertFallbackFor(json("10,30,"+"x".repeat(501)));}
 @Test void totalOverLimitAndCrossDayFallback(){request=new PlanDraftRequest(DATE,LocalTime.of(9,0),70,null);assertFallbackFor("{\"summary\":\"x\",\"items\":[{\"taskId\":10,\"plannedMinutes\":60,\"reason\":\"x\"},{\"taskId\":11,\"plannedMinutes\":45,\"reason\":\"x\"}]}");request=new PlanDraftRequest(DATE,LocalTime.of(23,30),60,null);assertEquals(ErrorCode.INVALID_PLAN_TIME,assertThrows(BusinessException.class,()->service.generate(request)).getErrorCode());}
 @Test void timeoutRateLimitAndUnavailableFallbackWithoutLeakingError(){for(ErrorCode code:List.of(ErrorCode.AI_PROVIDER_TIMEOUT,ErrorCode.AI_PROVIDER_RATE_LIMITED,ErrorCode.AI_PROVIDER_UNAVAILABLE)){available();when(contexts.build(1,DATE)).thenReturn(context());when(gateway.generate(anyString(),anyString())).thenThrow(new AiProviderException(code));var result=service.generate(request);assertTrue(result.fallbackUsed());assertFalse(result.fallbackReason().contains("test-key"));reset(gateway);}}
 private void assertFallbackFor(String content){available();when(contexts.build(1,DATE)).thenReturn(context());when(gateway.generate(anyString(),anyString())).thenReturn(content);var r=service.generate(request);assertTrue(r.fallbackUsed());assertEquals("RULE",r.generatorType());}
 private void available(){when(provider.getIfAvailable()).thenReturn(gateway);when(provider.getObject()).thenReturn(gateway);}private String json(String csv){String[]p=csv.split(",",3);return "{\"summary\":\"x\",\"items\":[{\"taskId\":"+p[0]+",\"plannedMinutes\":"+p[1]+",\"reason\":\""+(p.length>2?p[2]:"")+"\"}]}";}
 private AiPlanningContext context(){return new AiPlanningContext(List.of(),List.of(),List.of(task(10,60),task(11,45)),new AiPlanningContext.StudySummaryContext(0,0,0),List.of(),List.of());}private AiPlanningContext emptyContext(){return new AiPlanningContext(List.of(),List.of(),List.of(),new AiPlanningContext.StudySummaryContext(0,0,0),List.of(),List.of());}private AiPlanningContext.TaskContext task(long id,int minutes){return new AiPlanningContext.TaskContext(id,2L,"Java","#409EFF",null,null,"Task"+id,null,3,TaskStatus.TODO,minutes,DATE,null);}
}
