<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { planApi } from '../../api/plan'
import type { PlanDraft, PlanDraftItem, PlanDetail } from '../../types/plan'
import { addWallMinutes, shanghaiDate } from '../../utils/businessTime'
import { minutesLabel, nullableText } from '../../utils/display'
const emit=defineEmits<{confirmed:[plan:PlanDetail]}>()
const form=reactive({planDate:shanghaiDate(),startTime:'09:00:00',availableMinutes:120,requirement:''})
const draft=ref<PlanDraft|null>(null),original=ref<PlanDraft|null>(null),generating=ref(false),confirming=ref(false)
const remaining=computed(()=>draft.value?draft.value.availableMinutes-draft.value.plannedMinutes:0)
function clone(value:PlanDraft){return structuredClone(value)}
function recalculate(){if(!draft.value)return;let cursor=`${draft.value.planDate}T${draft.value.startTime}`;draft.value.items.forEach((item,index)=>{item.sequenceNo=index+1;item.startAt=cursor;item.endAt=addWallMinutes(cursor,item.plannedMinutes);cursor=item.endAt});draft.value.plannedMinutes=draft.value.items.reduce((sum,item)=>sum+item.plannedMinutes,0);draft.value.summary=`共安排${draft.value.items.length}项任务，计划学习${draft.value.plannedMinutes}分钟`}
function move(index:number,offset:number){if(!draft.value)return;const target=index+offset;if(target<0||target>=draft.value.items.length)return;[draft.value.items[index],draft.value.items[target]]=[draft.value.items[target],draft.value.items[index]];recalculate()}
function durationChanged(item:PlanDraftItem){item.plannedMinutes=Math.max(15,Math.round(item.plannedMinutes||15));recalculate();if(draft.value&&draft.value.plannedMinutes>draft.value.availableMinutes)ElMessage.warning('已安排时长不能超过可用时长')}
async function generate(){if(form.planDate<shanghaiDate())return ElMessage.warning('计划日期不能早于今天');if(form.availableMinutes<1||form.availableMinutes>720)return ElMessage.warning('可用时长必须为1至720分钟');const end=addWallMinutes(`${form.planDate}T${form.startTime}`,form.availableMinutes);if(end.slice(0,10)!==form.planDate)return ElMessage.warning('计划时间不能跨越自然日');generating.value=true;try{const result=(await planApi.generateDraft({...form,requirement:nullableText(form.requirement)})).data.data;draft.value=clone(result);original.value=clone(result)}finally{generating.value=false}}
async function confirm(){if(!draft.value?.items.length)return ElMessage.warning('空草案不能确认');if(draft.value.plannedMinutes>draft.value.availableMinutes)return ElMessage.warning('已安排时长超过可用时长');confirming.value=true;try{const plan=(await planApi.confirm({draftId:draft.value.draftId,planDate:draft.value.planDate,availableMinutes:draft.value.availableMinutes,plannedMinutes:draft.value.plannedMinutes,requirement:draft.value.requirement,summary:draft.value.summary,items:draft.value.items.map(({sequenceNo,taskId,startAt,endAt,plannedMinutes,reason})=>({sequenceNo,taskId,startAt,endAt,plannedMinutes,reason}))})).data.data;ElMessage.success('学习计划已保存');draft.value=null;original.value=null;emit('confirmed',plan)}finally{confirming.value=false}}
</script>
<template><div class="plan-builder"><el-card shadow="never" class="panel-card"><template #header><strong>生成计划</strong></template><el-form label-position="top"><div class="form-grid"><el-form-item label="计划日期"><el-date-picker v-model="form.planDate" type="date" value-format="YYYY-MM-DD" class="full-width" /></el-form-item><el-form-item label="开始时间（北京时间）"><el-time-picker v-model="form.startTime" value-format="HH:mm:ss" class="full-width" /></el-form-item></div><el-form-item label="可用学习时长"><el-radio-group v-model="form.availableMinutes"><el-radio-button v-for="m in [60,90,120,180]" :key="m" :value="m">{{m}}分钟</el-radio-button></el-radio-group><el-input-number v-model="form.availableMinutes" :min="1" :max="720" class="plan-custom-minutes" /></el-form-item><el-form-item label="补充要求"><el-input v-model="form.requirement" type="textarea" :rows="3" maxlength="1000" show-word-limit /></el-form-item><el-button type="primary" :loading="generating" @click="generate">生成计划草案</el-button></el-form></el-card>
<el-card shadow="never" class="panel-card"><template #header><div class="card-header"><strong>草案预览</strong><el-button v-if="original" text @click="draft=clone(original)">恢复生成结果</el-button></div></template><el-empty v-if="!draft" description="填写可用时间后生成规则计划"/><template v-else><div class="draft-summary"><span>草案 {{draft.draftId.slice(0,8)}}</span><strong>{{draft.summary}}</strong><small>可用 {{minutesLabel(draft.availableMinutes)}} · 已排 {{minutesLabel(draft.plannedMinutes)}} · 剩余 {{minutesLabel(remaining)}}</small></div><el-empty v-if="!draft.items.length" :description="draft.summary"/><div v-else class="draft-items"><article v-for="(item,index) in draft.items" :key="item.taskId" class="draft-item"><div class="draft-sequence">{{item.sequenceNo}}</div><div><strong><span class="color-dot" :style="{backgroundColor:item.subjectColor||'#94a3b8'}"/>{{item.taskTitle}}</strong><p>{{item.subjectName}} · {{item.startAt.slice(11,16)}}—{{item.endAt.slice(11,16)}} · {{item.reason}}</p></div><el-input-number v-model="item.plannedMinutes" :min="15" :max="draft.availableMinutes" size="small" @change="durationChanged(item)"/><div class="draft-actions"><el-button text :disabled="index===0" @click="move(index,-1)">上移</el-button><el-button text :disabled="index===draft.items.length-1" @click="move(index,1)">下移</el-button></div></article></div><el-button type="primary" class="plan-confirm" :disabled="!draft.items.length||draft.plannedMinutes>draft.availableMinutes" :loading="confirming" @click="confirm">确认并保存计划</el-button></template></el-card></div></template>
