<script setup lang="ts">
import{onMounted,reactive,ref}from'vue';import{ElMessage,ElMessageBox}from'element-plus';import{planApi}from'../../api/plan';import type{PlanDetail,PlanListItem,PlanStatus}from'../../types/plan';import{formatDateTime,minutesLabel}from'../../utils/display'
const emit=defineEmits<{detail:[plan:PlanDetail]}>();const rows=ref<PlanListItem[]>([]),total=ref(0),loading=ref(false);const query=reactive({page:1,pageSize:10,startDate:'',endDate:'',status:undefined as PlanStatus|undefined});const dateRange=ref<string[]|null>(null);const labels={CONFIRMED:'已确认',COMPLETED:'已完成',CANCELLED:'已取消'} as const
async function load(){loading.value=true;try{const page=(await planApi.list({page:query.page,pageSize:query.pageSize,startDate:dateRange.value?.[0]||undefined,endDate:dateRange.value?.[1]||undefined,status:query.status})).data.data;rows.value=page.list;total.value=page.total}finally{loading.value=false}}
async function detail(row:PlanListItem){emit('detail',(await planApi.get(row.id)).data.data)}
async function cancel(row:PlanListItem){try{await ElMessageBox.confirm('取消后不能继续更新计划项，确定吗？','取消计划',{type:'warning'});await planApi.changeStatus(row.id,'CANCELLED');ElMessage.success('计划已取消');load()}catch(error){if(error!=='cancel'&&error!=='close'){} }}
function reset(){dateRange.value=null;query.status=undefined;query.page=1;load()} defineExpose({load})
onMounted(load)
</script>
<template><el-card shadow="never" class="panel-card plan-history"><template #header><strong>历史计划</strong></template><div class="filter-bar"><el-date-picker v-model="dateRange" type="daterange" value-format="YYYY-MM-DD" start-placeholder="开始日期" end-placeholder="结束日期"/><el-select v-model="query.status" clearable placeholder="全部状态"><el-option v-for="(label,status) in labels" :key="status" :label="label" :value="status"/></el-select><el-button type="primary" @click="query.page=1;load()">查询</el-button><el-button @click="reset">重置</el-button></div><div class="table-scroll"><el-table v-loading="loading" :data="rows"><el-table-column prop="planDate" label="计划日期" width="115"/><el-table-column label="计划时长" width="150"><template #default="{row}">{{minutesLabel(row.plannedMinutes)}} / {{minutesLabel(row.availableMinutes)}}</template></el-table-column><el-table-column label="计划项" width="90"><template #default="{row}">{{row.totalItemCount}}项</template></el-table-column><el-table-column label="进度" min-width="150"><template #default="{row}"><el-progress :percentage="row.completionPercentage"/></template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><el-tag>{{labels[row.status as PlanStatus]}}</el-tag></template></el-table-column><el-table-column prop="summary" label="摘要" min-width="220" show-overflow-tooltip/><el-table-column label="创建时间" width="165"><template #default="{row}">{{formatDateTime(row.createdAt)}}</template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="{row}"><el-button link type="primary" @click="detail(row)">详情</el-button><el-button v-if="row.status==='CONFIRMED'" link type="danger" @click="cancel(row)">取消</el-button></template></el-table-column></el-table></div><div class="pagination"><el-pagination v-model:current-page="query.page" v-model:page-size="query.pageSize" :total="total" :page-sizes="[10,20,50]" layout="total, sizes, prev, pager, next" @change="load"/></div></el-card></template>
