export type LearningPathStatus = 'ACTIVE' | 'PAUSED' | 'COMPLETED' | 'CANCELLED'
export type LearningPathItemStatus = 'PENDING' | 'SKIPPED'
export interface LearningPathGenerateRequest { requirement:string; subjectId?:number|null; currentLevel?:string|null; targetLevel?:string|null; dailyMinutes?:number|null; startDate?:string|null; targetDate?:string|null; preferences?:string|null }
export interface LearningPathDraftItem { sequenceNo:number; topic:string; learningObjective:string; learningMethod:string[]; completionCriteria:string[]; estimatedMinutes:number; suggestedDay:number|null; prerequisite:string|null; reason:string|null }
export interface LearningPathDraftStage { stageNo:number; title:string; description:string|null; items:LearningPathDraftItem[] }
export interface LearningPathDraft { title:string; summary:string|null; subjectId:number|null; originalRequirement:string; currentLevel:string|null; targetLevel:string|null; dailyMinutes:number|null; startDate:string; targetDate:string|null; preferences:string|null; totalMinutes:number; stages:LearningPathDraftStage[] }
export interface LearningPathConfirmItem extends LearningPathDraftItem { stageNo:number; stageTitle:string; stageDescription:string|null }
export interface LearningPathConfirmRequest { subjectId:number|null; title:string; summary:string|null; originalRequirement:string; goal?:string|null; currentLevel:string|null; targetLevel:string|null; purpose?:string|null; preferences:string|null; startDate:string; targetDate:string|null; dailyMinutes:number|null; items:LearningPathConfirmItem[] }
export interface LearningPathListItem { id:number; subjectId:number|null; subjectName:string|null; subjectColor:string|null; title:string; status:LearningPathStatus; startDate:string; targetDate:string|null; stageCount:number; totalItems:number; completedItems:number; skippedItems:number; progress:number; currentStage:string|null; createdAt:string }
export interface LearningPathItem { id:number; sequenceNo:number; stageNo:number; stageTitle:string; stageDescription:string|null; topic:string; learningObjective:string; learningMethod:string[]; completionCriteria:string[]; estimatedMinutes:number; suggestedDay:number|null; prerequisite:string|null; reason:string|null; storedStatus:LearningPathItemStatus; effectiveStatus:'PENDING'|'COMPLETED'|'SKIPPED'; taskId:number|null; taskTitle:string|null; taskStatus:'TODO'|'IN_PROGRESS'|'COMPLETED'|'CANCELLED'|null }
export interface LearningPathDetail extends Omit<LearningPathListItem,'currentStage'> { summary:string|null; originalRequirement:string; goal:string|null; currentLevel:string|null; targetLevel:string|null; purpose:string|null; preferences:string|null; dailyMinutes:number|null; updatedAt:string; items:LearningPathItem[] }
export interface LearningPathTaskResult { pathId:number; itemId:number; taskId:number; taskTitle:string; created:boolean; message:string }
