CREATE TABLE `user` (
    id BIGINT NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_username (username),
    CONSTRAINT chk_user_status CHECK (status IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE subject (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NULL,
    color VARCHAR(20) NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_subject_user_name (user_id, name),
    KEY idx_subject_user_sort (user_id, sort_order),
    CONSTRAINT fk_subject_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE study_goal (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(1000) NULL,
    target_minutes INT NOT NULL,
    target_date DATE NULL,
    status VARCHAR(20) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_goal_user_status (user_id, status),
    KEY idx_goal_user_subject (user_id, subject_id),
    KEY idx_goal_user_target_date (user_id, target_date),
    CONSTRAINT chk_goal_target_minutes CHECK (target_minutes > 0),
    CONSTRAINT chk_goal_status CHECK (status IN ('ACTIVE', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT fk_goal_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_goal_subject FOREIGN KEY (subject_id) REFERENCES subject (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE study_task (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    goal_id BIGINT NULL,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(1000) NULL,
    priority TINYINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    estimated_minutes INT NOT NULL,
    planned_date DATE NULL,
    due_at DATETIME(3) NULL,
    completed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_task_user_status (user_id, status),
    KEY idx_task_user_planned (user_id, planned_date, status),
    KEY idx_task_user_due (user_id, due_at),
    KEY idx_task_user_priority_due (user_id, priority, due_at),
    KEY idx_task_user_subject (user_id, subject_id),
    KEY idx_task_user_goal (user_id, goal_id),
    CONSTRAINT chk_task_priority CHECK (priority BETWEEN 1 AND 4),
    CONSTRAINT chk_task_status CHECK (status IN ('TODO', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT chk_task_estimated_minutes CHECK (estimated_minutes > 0),
    CONSTRAINT chk_task_completion CHECK (status <> 'COMPLETED' OR completed_at IS NOT NULL),
    CONSTRAINT fk_task_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_task_subject FOREIGN KEY (subject_id) REFERENCES subject (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_task_goal FOREIGN KEY (goal_id) REFERENCES study_goal (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE study_record (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    task_id BIGINT NULL,
    started_at DATETIME(3) NOT NULL,
    ended_at DATETIME(3) NOT NULL,
    duration_minutes INT NOT NULL,
    feedback VARCHAR(1000) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_record_user_started (user_id, started_at),
    KEY idx_record_user_subject_started (user_id, subject_id, started_at),
    KEY idx_record_user_task (user_id, task_id),
    CONSTRAINT chk_record_time CHECK (ended_at > started_at),
    CONSTRAINT chk_record_duration CHECK (duration_minutes > 0),
    CONSTRAINT fk_record_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_record_subject FOREIGN KEY (subject_id) REFERENCES subject (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_record_task FOREIGN KEY (task_id) REFERENCES study_task (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE study_plan (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    source_draft_id VARCHAR(64) NOT NULL,
    plan_date DATE NOT NULL,
    available_minutes INT NOT NULL,
    planned_minutes INT NOT NULL,
    requirement VARCHAR(1000) NULL,
    summary VARCHAR(1000) NULL,
    status VARCHAR(20) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_plan_user_draft (user_id, source_draft_id),
    KEY idx_plan_user_date (user_id, plan_date),
    KEY idx_plan_user_status (user_id, status),
    CONSTRAINT chk_plan_available_minutes CHECK (available_minutes > 0),
    CONSTRAINT chk_plan_planned_minutes CHECK (planned_minutes > 0 AND planned_minutes <= available_minutes),
    CONSTRAINT chk_plan_status CHECK (status IN ('CONFIRMED', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT fk_plan_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE study_plan_item (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    plan_id BIGINT NOT NULL,
    task_id BIGINT NOT NULL,
    sequence_no INT NOT NULL,
    start_at DATETIME(3) NOT NULL,
    end_at DATETIME(3) NOT NULL,
    planned_minutes INT NOT NULL,
    reason VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_plan_item_sequence (plan_id, sequence_no),
    KEY idx_plan_item_user_task (user_id, task_id),
    KEY idx_plan_item_plan_time (plan_id, start_at),
    CONSTRAINT chk_plan_item_sequence CHECK (sequence_no > 0),
    CONSTRAINT chk_plan_item_time CHECK (end_at > start_at),
    CONSTRAINT chk_plan_item_minutes CHECK (planned_minutes > 0),
    CONSTRAINT chk_plan_item_status CHECK (status IN ('PENDING', 'COMPLETED', 'SKIPPED')),
    CONSTRAINT fk_plan_item_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_plan_item_plan FOREIGN KEY (plan_id) REFERENCES study_plan (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_plan_item_task FOREIGN KEY (task_id) REFERENCES study_task (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
