CREATE TABLE study_path (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    subject_id BIGINT NULL,
    title VARCHAR(200) NOT NULL,
    summary VARCHAR(1000) NULL,
    original_requirement VARCHAR(2000) NOT NULL,
    goal VARCHAR(500) NULL,
    current_level VARCHAR(200) NULL,
    target_level VARCHAR(200) NULL,
    purpose VARCHAR(500) NULL,
    preferences VARCHAR(1000) NULL,
    start_date DATE NOT NULL,
    target_date DATE NULL,
    daily_minutes INT NULL,
    status VARCHAR(20) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_path_user_status (user_id, status),
    KEY idx_path_user_subject (user_id, subject_id),
    KEY idx_path_user_dates (user_id, start_date, target_date),
    CONSTRAINT fk_path_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_path_subject FOREIGN KEY (subject_id) REFERENCES subject (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE study_path_item (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    path_id BIGINT NOT NULL,
    sequence_no INT NOT NULL,
    stage_no INT NOT NULL,
    stage_title VARCHAR(200) NOT NULL,
    stage_description VARCHAR(1000) NULL,
    topic VARCHAR(200) NOT NULL,
    learning_objective VARCHAR(1000) NOT NULL,
    learning_method TEXT NOT NULL,
    completion_criteria TEXT NOT NULL,
    estimated_minutes INT NOT NULL,
    suggested_day INT NULL,
    prerequisite_text VARCHAR(500) NULL,
    reason VARCHAR(500) NULL,
    status VARCHAR(20) NOT NULL,
    task_id BIGINT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_path_item_sequence (path_id, sequence_no),
    UNIQUE KEY uk_path_item_task (task_id),
    KEY idx_path_item_user_path (user_id, path_id),
    KEY idx_path_item_path_stage (path_id, stage_no, sequence_no),
    CONSTRAINT fk_path_item_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_path_item_path FOREIGN KEY (path_id) REFERENCES study_path (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_path_item_task FOREIGN KEY (task_id) REFERENCES study_task (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
