package com.yhk.aistudyplanner.plan.service;
import com.yhk.aistudyplanner.common.exception.*;import com.yhk.aistudyplanner.plan.dto.PlanDraftRequest;import com.yhk.aistudyplanner.plan.mapper.StudyPlanMapper;import com.yhk.aistudyplanner.plan.vo.PlanTaskCandidate;import com.yhk.aistudyplanner.task.entity.TaskStatus;
import org.junit.jupiter.api.*;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.Mock;import org.mockito.junit.jupiter.MockitoExtension;import java.time.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class) class RuleBasedPlanGeneratorTest{
 @Mock StudyPlanMapper mapper; RuleBasedPlanGenerator generator; static final LocalDate TODAY=LocalDate.of(2026,7,23);
 @BeforeEach void setUp(){Clock clock=Clock.fixed(TODAY.atStartOfDay(ZoneId.of("Asia/Shanghai")).toInstant(),ZoneId.of("Asia/Shanghai"));generator=new RuleBasedPlanGenerator(mapper,clock);}
 @Test void emptyTasksReturnClearEmptyDraft(){when(mapper.selectCandidates(1,TODAY,TODAY.atStartOfDay())).thenReturn(List.of());var result=generator.generate(1,new PlanDraftRequest(TODAY,LocalTime.of(9,0),120,null));assertTrue(result.items().isEmpty());assertEquals(0,result.plannedMinutes());assertTrue(result.summary().contains("暂无"));}
 @Test void truncatesLastTaskAndNeverExceedsAvailableTime(){when(mapper.selectCandidates(anyLong(),any(),any())).thenReturn(List.of(task(1,90,4,TaskStatus.TODO),task(2,90,2,TaskStatus.IN_PROGRESS)));var result=generator.generate(1,new PlanDraftRequest(TODAY,LocalTime.of(9,0),120,null));assertEquals(List.of(90,30),result.items().stream().map(i->i.plannedMinutes()).toList());assertEquals(120,result.plannedMinutes());assertEquals(result.items().get(0).endAt(),result.items().get(1).startAt());}
 @Test void stopsWhenRemainingIsBelowFifteenMinutes(){when(mapper.selectCandidates(anyLong(),any(),any())).thenReturn(List.of(task(1,110,4,TaskStatus.TODO),task(2,30,2,TaskStatus.TODO)));var result=generator.generate(1,new PlanDraftRequest(TODAY,LocalTime.of(9,0),120,null));assertEquals(1,result.items().size());assertEquals(110,result.plannedMinutes());}
 @Test void rejectsPastDateAndCrossDay(){assertEquals(ErrorCode.PLAN_DATE_IN_PAST,assertThrows(BusinessException.class,()->generator.generate(1,new PlanDraftRequest(TODAY.minusDays(1),LocalTime.NOON,60,null))).getErrorCode());assertEquals(ErrorCode.INVALID_PLAN_TIME,assertThrows(BusinessException.class,()->generator.generate(1,new PlanDraftRequest(TODAY,LocalTime.of(23,0),120,null))).getErrorCode());}
 @Test void usesCurrentUserInCandidateQuery(){when(mapper.selectCandidates(9,TODAY,TODAY.atStartOfDay())).thenReturn(List.of(task(1,30,3,TaskStatus.TODO)));generator.generate(9,new PlanDraftRequest(TODAY,LocalTime.of(9,0),60,null));verify(mapper).selectCandidates(9,TODAY,TODAY.atStartOfDay());}
 private PlanTaskCandidate task(long id,int minutes,int priority,TaskStatus status){return new PlanTaskCandidate(id,"任务"+id,2L,"Java","#409EFF",priority,status,minutes,TODAY,TODAY.plusDays(1).atStartOfDay());}
}
