package com.yhk.aistudyplanner.plan.service;
import com.baomidou.mybatisplus.core.MybatisConfiguration;import com.baomidou.mybatisplus.core.metadata.TableInfoHelper;import org.apache.ibatis.builder.MapperBuilderAssistant;
import com.yhk.aistudyplanner.auth.service.AuthSessionService;import com.yhk.aistudyplanner.common.exception.*;import com.yhk.aistudyplanner.plan.dto.*;import com.yhk.aistudyplanner.plan.entity.*;import com.yhk.aistudyplanner.plan.mapper.*;import com.yhk.aistudyplanner.task.entity.*;import com.yhk.aistudyplanner.task.mapper.TaskMapper;
import org.junit.jupiter.api.*;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;import org.mockito.junit.jupiter.MockitoExtension;import java.time.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class) class StudyPlanServiceTest{
 @Mock StudyPlanMapper planMapper;@Mock StudyPlanItemMapper itemMapper;@Mock TaskMapper taskMapper;@Mock AuthSessionService session;@Mock RuleBasedPlanGenerator generator;StudyPlanService service;static final LocalDate DATE=LocalDate.of(2026,7,23);static final LocalDateTime NOW=DATE.atTime(8,0);
 @BeforeEach void setUp(){TableInfoHelper.initTableInfo(new MapperBuilderAssistant(new MybatisConfiguration(),""),StudyPlan.class);TableInfoHelper.initTableInfo(new MapperBuilderAssistant(new MybatisConfiguration(),""),StudyPlanItem.class);TableInfoHelper.initTableInfo(new MapperBuilderAssistant(new MybatisConfiguration(),""),StudyTask.class);Clock clock=Clock.fixed(NOW.atZone(ZoneId.of("Asia/Shanghai")).toInstant(),ZoneId.of("Asia/Shanghai"));service=new StudyPlanService(planMapper,itemMapper,taskMapper,session,generator,clock);lenient().when(session.currentUserId()).thenReturn(1L);}
 @Test void confirmsPlanInOneLogicalOperation(){when(planMapper.selectOne(any())).thenReturn(null);when(taskMapper.selectList(any())).thenReturn(List.of(task(10),task(11)));doAnswer(i->{((StudyPlan)i.getArgument(0)).setId(7L);return 1;}).when(planMapper).insert(any(StudyPlan.class));when(itemMapper.selectViews(7,1)).thenReturn(List.of());var result=service.confirm(request("draft-1",List.of(item(1,10,9,60),item(2,11,10,30)),90));assertEquals(PlanStatus.CONFIRMED,result.status());verify(itemMapper,times(2)).insert(any(StudyPlanItem.class));}
 @Test void repeatedDraftReturnsExistingWithoutInsert(){StudyPlan existing=plan(7,PlanStatus.CONFIRMED);when(planMapper.selectOne(any())).thenReturn(existing);when(itemMapper.selectViews(7,1)).thenReturn(List.of());assertEquals(7,service.confirm(request("same",List.of(item(1,10,9,60)),60)).id());verify(planMapper,never()).insert(any(StudyPlan.class));}
 @Test void rejectsDuplicateTask(){when(planMapper.selectOne(any())).thenReturn(null);var ex=assertThrows(BusinessException.class,()->service.confirm(request("d",List.of(item(1,10,9,30),item(2,10,10,30)),60)));assertEquals(ErrorCode.PLAN_TASK_DUPLICATED,ex.getErrorCode());}
 @Test void rejectsOverlapAndDurationMismatch(){when(planMapper.selectOne(any())).thenReturn(null);var overlap=List.of(new PlanConfirmItemRequest(1,10L,DATE.atTime(9,0),DATE.atTime(10,0),60,"原因"),new PlanConfirmItemRequest(2,11L,DATE.atTime(9,30),DATE.atTime(10,30),60,"原因"));assertEquals(ErrorCode.PLAN_TIME_OVERLAP,assertThrows(BusinessException.class,()->service.confirm(request("d",overlap,120))).getErrorCode());assertEquals(ErrorCode.INVALID_PLAN_DURATION,assertThrows(BusinessException.class,()->service.confirm(request("x",List.of(new PlanConfirmItemRequest(1,10L,DATE.atTime(9,0),DATE.atTime(10,0),30,"原因")),30))).getErrorCode());}
 @Test void rejectsInvalidTaskOwnershipOrStatus(){when(planMapper.selectOne(any())).thenReturn(null);when(taskMapper.selectList(any())).thenReturn(List.of());assertEquals(ErrorCode.PLAN_TASK_INVALID,assertThrows(BusinessException.class,()->service.confirm(request("d",List.of(item(1,10,9,60)),60))).getErrorCode());}
 @Test void cancelAndCancelledItemMutationRules(){StudyPlan plan=plan(7,PlanStatus.CONFIRMED);when(planMapper.selectOne(any())).thenReturn(plan);when(planMapper.update(isNull(),any())).thenReturn(1);when(itemMapper.selectViews(7,1)).thenReturn(List.of());assertEquals(PlanStatus.CANCELLED,service.changeStatus(7,new PlanStatusRequest(PlanStatus.CANCELLED)).status());plan.setStatus(PlanStatus.CANCELLED);assertEquals(ErrorCode.PLAN_ALREADY_CANCELLED,assertThrows(BusinessException.class,()->service.changeItemStatus(7,2,new PlanItemStatusRequest(PlanItemStatus.COMPLETED))).getErrorCode());}
 @Test void itemCompletionAndRestoreRecalculatePlan(){StudyPlan plan=plan(7,PlanStatus.CONFIRMED);StudyPlanItem item=new StudyPlanItem();item.setId(2L);item.setPlanId(7L);item.setUserId(1L);item.setStatus(PlanItemStatus.PENDING);when(planMapper.selectOne(any())).thenReturn(plan);when(itemMapper.selectOne(any())).thenReturn(item);when(itemMapper.update(isNull(),any())).thenReturn(1);when(itemMapper.selectCount(any())).thenReturn(0L);when(planMapper.update(isNull(),any())).thenReturn(1);when(itemMapper.selectViews(7,1)).thenReturn(List.of());assertEquals(PlanStatus.COMPLETED,service.changeItemStatus(7,2,new PlanItemStatusRequest(PlanItemStatus.COMPLETED)).status());item.setStatus(PlanItemStatus.COMPLETED);plan.setStatus(PlanStatus.COMPLETED);when(itemMapper.selectCount(any())).thenReturn(1L);assertEquals(PlanStatus.CONFIRMED,service.changeItemStatus(7,2,new PlanItemStatusRequest(PlanItemStatus.PENDING)).status());}
 private PlanConfirmRequest request(String id,List<PlanConfirmItemRequest>items,int total){return new PlanConfirmRequest(id,DATE,120,total,null,"摘要",items);}private PlanConfirmItemRequest item(int seq,long task,int hour,int min){return new PlanConfirmItemRequest(seq,task,DATE.atTime(hour,0),DATE.atTime(hour,0).plusMinutes(min),min,"原因");}
 private StudyTask task(long id){StudyTask t=new StudyTask();t.setId(id);t.setUserId(1L);t.setStatus(TaskStatus.TODO);return t;}private StudyPlan plan(long id,PlanStatus status){StudyPlan p=new StudyPlan();p.setId(id);p.setUserId(1L);p.setSourceDraftId("d");p.setPlanDate(DATE);p.setAvailableMinutes(120);p.setPlannedMinutes(60);p.setSummary("摘要");p.setStatus(status);p.setCreatedAt(NOW);p.setUpdatedAt(NOW);return p;}
}
